### ISSUE TITLE
On Windows, when pressing enter after choosing semester,  'Input not an integer' will be raised.

### ISSUE THREAD

**Issue by wusitee** [hey2022/tls-xb#36]
Whether or not the number is input, the error will be raised.
```
Choose a semester [1]:
thread 'main' panicked at src\main.rs:122:42:
Input not an integer: ParseIntError { kind: InvalidDigit }
note: run with `RUST_BACKTRACE=1` environment variable to displaythread 'main' panicked at src\main.rs:122:42:
```
```
Choose a semester [1]: 1
thread 'main' panicked at src\main.rs:122:42:
Input not an integer: ParseIntError { kind: InvalidDigit }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
It can be reproduced on tls-xb 0.3.4 .

**Comment by hey2022** [comment]
Should be fixed, reopen if necessary.
